@startuml

title "Osmalert:  Draft of Sequence Diagram"

participant User
participant Browser
participant WebApp
participant Database
participant "Flink Cluster" as Flink
participant Kafka
participant Email

User -> Browser:
Browser -> WebApp:
WebApp -> Database:Job Jar
Database --> WebApp:
WebApp -> Flink:  Job Jar
Flink -> Kafka:
Kafka -> Flink:
Flink -> Email:
Email -> User:

@enduml