@startuml

cloud "OSM planet server"
queue Flink
folder job1
folder job2
folder job3

"OSM planet server"-[#red]-> Flink : All OSM changes
Flink --> job1
Flink --> job2
Flink --> job3: Filtered OSM changes by bounding box and Tags

@enduml