name: Build and Test

# on: workflow_dispatch

on:
    push:
        branches: [ main ]
#    pull_request:
#        branches: [ main ]

jobs:

    build-and-test-app:
        runs-on: ubuntu-latest

        name: Build and Test App

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '17'
                    cache: 'gradle'

            -   name: Build and test with Gradle
                run: ./gradlew check --no-daemon

            -   name: Notify Discord on Failure
                if: always()
                env:
                    DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/1159801100099129354/obrNG3ZxTPISnIzDsrErXGiROR_w5OLwE2IJ7ad0MKwU7LOiD85eLSI3XjmBVNKZV0ts'
                run: |
                    curl -X POST -H "Content-Type: application/json" -d '{
                      "content": "Build Failed! :x:"
                    }' $DISCORD_WEBHOOK

