name: Build and Test

# on: workflow_dispatch

on:
    push:
        branches: [ main ]
#    pull_request:
#        branches: [ main ]

jobs:

    build-and-test-app:
        runs-on: ubuntu-latest

        name: Build and Test App

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '17'
                    cache: 'gradle'

            -   name: Build and test with Gradle
                run: ./gradlew check --no-daemon

    notify:
        name: Discord Notification
        runs-on: ubuntu-latest
        needs:
            - build-and-test-app
        if: failure()
        steps:
            -   name: Notify
                uses: nobrayner/discord-webhook@v1
                with:
                    github-token: ${{ secrets.github_token }}
                    discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
                    avatar-url: 'https://www.openstreetmap.org/assets/osm_logo-4afddaae0230a5a46687fdc751ed256dfdccde144118cb02a7d7960f207a4b92.svg'